version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA#
      PGDATA: /data/postgres
    ports:
      - "8084:5432"